// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhfpfjaduvylexhfxnky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZnBmamFkdXZ5bGV4aGZ4bmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzk4NDEsImV4cCI6MjA2NzgxNTg0MX0.FX2q1akBrgAHYmTvJh_iA_57EJd8kuQAMTEXdaixEtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});